### ISSUE TITLE
What should PREFIX be set to?

### ISSUE THREAD

**Issue by initrd** [alexiri/docker-fava#2]
Without setting PREFIX, the wsgi app fails:

```
fava    | Traceback (most recent call last):
fava    |   File "./main.py", line 7, in <module>
fava    |     prefix = os.environ['PREFIX']
fava    |   File "/usr/lib/python3.6/os.py", line 669, in __getitem__
fava    |     raise KeyError(key) from None
fava    | KeyError: 'PREFIX'
fava    | unable to load app 0 (mountpoint='') (callable not found or import error)
fava    | *** no app loaded. GAME OVER ***
fava    | 2019-09-03 16:12:37,294 INFO exited: uwsgi (exit status 22; not expected)
fava    | 2019-09-03 16:12:38,296 INFO gave up: uwsgi entered FATAL state, too many start retries too quickly
```

Setting PREFIX to `/app` does not throw the error but the app loads blank without any error messages.

**Comment by initrd** [comment]
Never mind, figured this out reading [deployment.rst](https://github.com/beancount/fava/blob/master/contrib/deployment.rst). Thank you for the image, it works great! :)
